<div class="text-content">
    <h2><?php echo _("About") ?></h2>
<p>
<?php 
echo sprintf(_("%sDJ Pro Cloud%s %s, the open radio software for scheduling and remote station management. %s"),
    "<a href='http://www.axeltechnology.com' target='_blank'>",
    "</a>",
     $this->airtime_version,
    "<br />")
?>
<br>© 2013 
<?php 
echo sprintf(_("%sAxel Technology%s"),
    "<a href='http://www.axeltechnology.com' target='_blank'>",
    "</a>")
?>
</p>
</div>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
